### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by meinja** [sm3ulc/hab-wspr#1]
I'm getting an error when running the script in Windows 7.  Not sure how to fix it:

![image](https://user-images.githubusercontent.com/43411482/68948042-697ffc80-078d-11ea-9bb9-85d6ef9dfbf3.png)

**Comment by sm3ulc** [comment]
Can you share your file "balloon.ini"?

**Comment by N2NXZ-11** [comment]
I am also using Windows 7 x 64 and tried several versions of Python,same errors.
It tries to work,then stops.
Maybe because you are already running the script for N2NXZ already ?
Jim

**Comment by N2NXZ-11** [comment]
Here is my INI - 
[main]
push_habhub = True
habhub_callsign = "U3S35"

push_aprs = True
aprsCallsign = "N2NXZ-12"
aprsUser = 'N2NXZ' # Replace with your own callsign. This should NOT have any SSID's on it (i.e. -9)
aprsPass = '10632' # APRS-IS passcode for your callsign.

balloons = [[ "U3S35","N2NXZ",14,5]]

**Comment by N2NXZ-11** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd C:\Users\Jim\AppData\Local\Programs\Python\Python38-32\Ha
bScipts\hab-wspr-master

C:\Users\Jim\AppData\Local\Programs\Python\Python38-32\HabScipts\hab-wspr-master
>py webscrape.py
Tracking these balloons:
['U3S35', 'N2NXZ', 14, 5]
Preloading cache from wsprnet...
Fspots1 10000
Fspots2 9
Entering pollingloop.
pre-tele: 5
2019-11-19 05:23:32 Name: U3S35  Call:  N2NXZ MHz: 14 Channel:  5 Spots: 5 Telem
etry: 1
2019-11-19 05:23:32 Spots:     5 Cache:      9 New:     0 (max:     0) Nrspots:
 2000 Looptime: 05.647210 Checks:        9
Traceback (most recent call last):
  File "webscrape.py", line 255, in <module>
    sleeping = sleeptime - int(datetime.datetime.now().strftime('%s')) % sleepti
me
ValueError: Invalid format string

C:\Users\Jim\AppData\Local\Programs\Python\Python38-32\HabScipts\hab-wspr-master
>

**Comment by sm3ulc** [comment]
This should be without SSID. Have updated the .ini

> aprsCallsign = "N2NXZ-12"

**Comment by sm3ulc** [comment]
> Microsoft Windows [Version 6.1.7601]
> Copyright (c) 2009 Microsoft Corporation. All rights reserved.
> 
> C:\Windows\system32>cd C:\Users\Jim\AppData\Local\Programs\Python\Python38-32\Ha
> bScipts\hab-wspr-master
> 
> C:\Users\Jim\AppData\Local\Programs\Python\Python38-32\HabScipts\hab-wspr-master
> 
> > py webscrape.py
> > Tracking these balloons:
> > ['U3S35', 'N2NXZ', 14, 5]
> > Preloading cache from wsprnet...
> > Fspots1 10000
> > Fspots2 9
> > Entering pollingloop.
> > pre-tele: 5
> > 2019-11-19 05:23:32 Name: U3S35  Call:  N2NXZ MHz: 14 Channel:  5 Spots: 5 Telem
> > etry: 1
> > 2019-11-19 05:23:32 Spots:     5 Cache:      9 New:     0 (max:     0) Nrspots:
> > 2000 Looptime: 05.647210 Checks:        9
> > Traceback (most recent call last):
> > File "webscrape.py", line 255, in 
> > sleeping = sleeptime - int(datetime.datetime.now().strftime('%s')) % sleepti
> > me
> > ValueError: Invalid format string
> 
> C:\Users\Jim\AppData\Local\Programs\Python\Python38-32\HabScipts\hab-wspr-master
> 
> >

Have not seen that error and it's from a standard-library. Should work fine in any version of python.

**Comment by N2NXZ-11** [comment]
Yes...Mikael said you change this in INI.
He said to not use -12 but -11 instead but I am using that on APRS flight
currently.
I posted to your Github page -
https://github.com/sm3ulc/hab-wspr/issues/1
I have setup for IZ7VHF / Ch 16 / LUISA1 for Roberto and trying to run
script but it also does not work for me.
I do not know if it is Windows 7 issue or something I am doing wrong in INI.
I am interested in using this script.
Jim

I have INI like this -
[main]
push_habhub = True
habhub_callsign = "Luisa1"

push_aprs = True
aprsCallsign = "IZ7VHF-11"
aprsUser = 'IZ7VHF' # Replace with your own callsign. This should NOT have
any SSID's on it (i.e. -9)
aprsPass = '17832' # APRS-IS passcode for your callsign.

balloons = [["LUISA1","IZ7VHF",14,16]]

**Comment by N2NXZ-11** [comment]
I will try Windows 10 computer,maybe the Windows 7 x 64 no good.

**Comment by sm3ulc** [comment]
I only run in linux environment and have never tried any Python in Windows.

**Comment by sm3ulc** [comment]
Use "aprsCallsign = "IZ7VHF", no ssid because it's the object transmitter.

balloons = [["LUISA1","IZ7VHF ... 
=>  IZ7VHF-12 as balloon ham call

**Comment by N2NXZ-11** [comment]
Maybe that is the issue David...I will remove -11 OR -12 from this INI.
I have just installed on Win 10 computer and receive same error
messages...so maybe it is this INI.
I will try this now.

**Comment by N2NXZ-11** [comment]
So here is INI setup now.
And still looks like it want to run,then stops?
Do you think I crated proper flight document for GENPAYLOAD for LUISA-1 ?
=========================
[main]
push_habhub = True
habhub_callsign = "Luisa1"

push_aprs = True
aprsCallsign = "IZ7VHF"
aprsUser = 'IZ7VHF' # Replace with your own callsign. This should NOT have
any SSID's on it (i.e. -9)
aprsPass = '17832' # APRS-IS passcode for your callsign.

balloons = [["LUISA1","IZ7VHF",14,16]]
=========================

[image: Capture.JPG]

**Comment by N2NXZ-11** [comment]
I think the issue is Windows Python...may go an install a copy of Linux on
my spare machine and try this.

**Comment by meinja** [comment]
Still getting errors.  Running it in Debian-based Linux.

**Comment by meinja** [comment]
Still getting errors.  Running it in a Debian-based Linux distro:

kp3ft@kp3ft:~/hab-wspr$ sudo python3 webscrape.py
Tracking these balloons:
['LUISA-1', 'IZ7VHF', 14, 16]
Preloading cache from wsprnet...
Fspots1 10000
Fspots2 2
Entering pollingloop.
pre-tele: 2
2019-11-19 11:46:12 Name: LUISA-1 Call: IZ7VHF MHz: 14 Channel: 16 Spots: 2 Telemetry: 1
2019-11-19 11:46:12 call IZ7VHF time 2019-11-19 20:42:00 fq 14.097052 loc -4 power FN13 reporter 10
2019-11-19 11:46:12 Spots:     2 Cache:      2 New:     0 (max:     0) Nrspots:  2000 Looptime: 07.449057 Checks:        2
New [datetime.datetime(2019, 11, 19, 20, 44), 'Q36IXJ', '14.097050', '+5', '-1', 'KO43', 57, 'SWLNXZ', 'FN13bi', '7201']
pre-tele: 3
2019-11-19 11:47:04 Name: LUISA-1 Call: IZ7VHF MHz: 14 Channel: 16 Spots: 3 Telemetry: 2
2019-11-19 11:47:04 call IZ7VHF time 2019-11-19 20:42:00 fq 14.097052 loc -4 power FN13 reporter 10
call IZ7VHF time 2019-11-19 20:42:00 fq 14.097052 loc -4 power FN13 reporter 10
2019-11-19 20:42:00 Call: IZ7VHF Latlon:   43.31250  -77.79167 Loc: FN13ch Alt:    60 Temp:   2.88 Batt:  4.90 Speed:   0 GPS:         1 Sats: 0
Removing: [datetime.datetime(2019, 11, 19, 20, 44), 'Q36IXJ', '14.097050', '+5', '-1', 'KO43', 57, 'SWLNXZ', 'FN13bi', '7201']
Database error: no such table: sentspots
Pushing data to habhub
Traceback (most recent call last):
  File "webscrape.py", line 235, in <module>
    spots = process_telemetry(spots, balloons,habhub_callsign, push_habhub, push_aprs)
  File "/home/kp3ft/hab-wspr/telemetry.py", line 621, in process_telemetry
    send_tlm_to_habitat(telestr, habhub_callsign, spot_time)
  File "/home/kp3ft/hab-wspr/telemetry.py", line 402, in send_tlm_to_habitat
    uri="http://habitat.habhub.org:/habitat/_design/payload_telemetry/_update/add_listener/%s" % sha256(sentence2).hexdigest()        ,
NameError: name 'sha256' is not defined
kp3ft@kp3ft:~/hab-wspr$

**Comment by meinja** [comment]
Using this balloon.ini text:

[main]
push_habhub = True
habhub_callsign = "LUISA-1"

push_aprs = True

# This is the callsign the object comes from. This should NOT have any SSID's on it (i.e. -9)
aprsCallsign = "IZ7VHF"
# Replace with your own callsign. This should NOT have any SSID's on it (i.e. -9)
aprsUser = 'IZ7VHF'
# APRS-IS passcode for your callsign.
aprsPass = '17832'

# [ habhub name, aprs-call, band in mhz, channel ]
balloons = [[ "LUISA-1","IZ7VHF",14,16]]

**Comment by sm3ulc** [comment]
Something looks missing in the parser conf. There's no "$$Luisa1.... " as
the other flights have. Check with the #habhub channel.

**Comment by meinja** [comment]
Can you post an INI file you are using for a flight that works?  that way I can see if I have anything wrong in mine, like syntax or whatever.

**Comment by N2NXZ-11** [comment]
I setup Luisa1 in GENPAYLOAD carefully and looked over U3S35 that works and copied it manually.
I see $$LUISA1 in the parser now.
![5](https://user-images.githubusercontent.com/57942884/69233444-ec70d080-0b5a-11ea-95e8-eaa5a92ed8bb.JPG)
