### ISSUE TITLE
webscrape.py appears to be always in dry_run mode

### ISSUE THREAD

**Issue by zanco** [sm3ulc/hab-wspr#4]
`

csv_file = ''
--
148 | conf_file = 'balloon.ini'
149 | dry_run = True
150 |  
151 | print("ARGV      :", sys.argv[1:])
152 |  
153 | try:
154 | options, remainder = getopt.getopt(
… |  
176 | if opt in ('--dry_run'):
177 | dry_run = True
178 | elif opt in ('-v', '--verbose'):
179 | verbose = True

`
After changing line 149 to dry_run = False the spots get uploaded.

On my ubuntu 18 system options like --verbose and --dry_run do give an error message, -v does work. Same error on Pi3 with all update / upgrades

print('ERROR:' , erxe) Name Errror : name erxr is not defined

**Comment by sm3ulc** [comment]
Thanks, fixed!
